import type { SiteContent } from './types'

export const defaultContent: SiteContent = {
  theme: {
    logoImageUrl: '',
    logoText: 'NMTECH',
    logoSubtext: 'Solutions',
  },
  sections: {
    hero: true,
    marquee: true,
    problem: true,
    services: true,
    projects: true,
    industry: true,
    process: true,
    differentiators: true,
    beforeAfter: true,
    pricing: true,
    testimonials: false,
    contact: true,
    about: true,
    ctaFinal: true,
  },
  hero: {
    eyebrow: 'Diseño & desarrollo web',
    titleLine1: 'Tu negocio merece',
    titleHighlight: 'una web a su altura.',
    description:
      'Diseñamos y desarrollamos páginas web modernas para negocios que quieren verse profesionales, generar confianza y conseguir más clientes.',
    cta1Label: 'Quiero mi página web',
    cta2Label: 'Ver proyectos',
    trustBadges: ['Diseño personalizado', 'Responsive', 'Optimizada para Google', 'Sin plantillas genéricas'],
    stats: [],
  },
  marquee: {
    keywords: [
      'Diseño web',
      'Desarrollo a medida',
      'SEO básico',
      'WhatsApp',
      'Google Maps',
      'Identidad digital',
      'Responsive',
      'Mantenimiento',
    ],
  },
  problem: {
    eyebrow: 'Antes de que digas una palabra',
    headline: 'Tu web habla de tu negocio antes que vos.',
    text:
      'Hoy un potencial cliente busca tu negocio en Google, Instagram o Maps y en segundos decide si confía en vos. Una página desactualizada — o no tener una — puede hacer que el cliente termine eligiendo a otro.',
    badLabel: 'Presencia improvisada',
    badItems: [
      'Solo un perfil de Instagram sin actualizar',
      'Nadie te encuentra buscando en Google',
      'Fotos del celular como único catálogo',
      'El cliente duda antes de escribirte',
    ],
    goodLabel: 'Negocio realmente profesional',
    goodItems: [
      'Una web propia que transmite seriedad',
      'Aparecés cuando te buscan en Google',
      'Tu trabajo mostrado con orden y calidad',
      'El cliente te escribe con confianza',
    ],
  },
  services: [
    { num: '01', name: 'Landing Pages', icon: 'landing', desc: 'Una sola página enfocada 100% en conseguir contactos. Ideal para promociones, lanzamientos o negocios que recién empiezan a tener presencia digital.' },
    { num: '02', name: 'Páginas institucionales', icon: 'institutional', desc: 'La carta de presentación de tu negocio: quiénes son, qué hacen y por qué elegirlos. Perfecta para profesionales, estudios y empresas de servicios.' },
    { num: '03', name: 'Catálogos digitales', icon: 'catalog', desc: 'Mostrá tus productos o servicios de forma ordenada y atractiva, con fotos y categorías fáciles de navegar desde el celular.' },
    { num: '04', name: 'Páginas para profesionales', icon: 'professional', desc: 'Consultorios, estudios y despachos que necesitan transmitir confianza desde el primer segundo, con turnos y contacto a un clic.' },
    { num: '05', name: 'Webs para comercios', icon: 'store', desc: 'Para que tu local se encuentre en Google igual de bien que en la vereda: ubicación, horarios y contacto siempre a mano.' },
    { num: '06', name: 'Integraciones', icon: 'integrations', desc: 'Conectamos tu web con WhatsApp, Google Maps, Instagram y las herramientas que ya usás, para que todo funcione desde un mismo lugar.' },
    { num: '07', name: 'Automatizaciones', icon: 'automation', desc: 'Mensajes de bienvenida, formularios y turnos automáticos: menos tareas manuales, más tiempo para tu negocio.' },
    { num: '08', name: 'Mantenimiento', icon: 'maintenance', desc: 'Tu web actualizada, funcionando y protegida todo el año, sin que tengas que preocuparte por la parte técnica.' },
  ],
  projects: [
    {
      category: 'Fitness / Gimnasio',
      name: 'IronCore Performance',
      image: '/projects/ironcoregym.jpg',
      url: 'https://ironcoregym-nmtech.vercel.app/',
      caption: 'Diseño oscuro y potente para gimnasios y entrenadores que quieren transmitir fuerza y resultados desde el primer segundo.',
      featured: true,
    },
    {
      category: 'Servicios / Corporativo',
      name: 'NMTECH Solutions v1',
      image: '/projects/nmtech-lp-v1.jpg',
      url: 'https://nmtech-lp-v1.vercel.app/',
      caption: 'Estilo sobrio y corporativo, ideal para empresas de servicios que necesitan transmitir seriedad y confianza.',
      featured: true,
    },
    {
      category: 'Servicios / Tecnología',
      name: 'NMTECH Solutions v2',
      image: '/projects/nmtech-lp-v2.jpg',
      url: 'https://nmtech-lp-v2.vercel.app/',
      caption: 'Un toque técnico con detalles tipo terminal, pensado para negocios de datos, software o desarrollo.',
      featured: true,
    },
    {
      category: 'Servicios / Minimalista',
      name: 'NMTECH Solutions v3',
      image: '/projects/nmtech-lp-v3.jpg',
      url: 'https://nmtech-lp-v3.vercel.app/',
      caption: 'Diseño claro, limpio y minimalista para marcas que prefieren un estilo más liviano que oscuro.',
      featured: false,
    },
    {
      category: 'E-commerce / Catálogo',
      name: 'Dinax Tech',
      image: '/projects/dinaxtech.jpg',
      url: 'https://dinaxtech.vercel.app/',
      caption: 'Catálogo digital pensado para tiendas de productos físicos, con consulta directa por WhatsApp.',
      featured: true,
    },
  ],
  industry: {
    eyebrow: 'Así podría verse tu negocio',
    headline: 'Imaginá tu negocio con una web así.',
    text: 'Trabajamos el diseño según el rubro: cada tipo de negocio necesita transmitir algo distinto. Esto es lo que podemos crear para el tuyo.',
    items: [
      { icon: 'cafe', label: 'Cafeterías' },
      { icon: 'gym', label: 'Gimnasios' },
      { icon: 'barber', label: 'Barberías' },
      { icon: 'realestate', label: 'Inmobiliarias' },
      { icon: 'dental', label: 'Odontología' },
      { icon: 'restaurant', label: 'Restaurantes' },
      { icon: 'store', label: 'Comercios locales' },
      { icon: 'professional', label: 'Profesionales' },
    ],
    ctaLabel: 'Quiero algo así para mi negocio',
  },
  process: [
    { num: '01', title: 'Nos contás tu idea', desc: 'Una charla simple, sin tecnicismos, para entender tu negocio y lo que necesitás.' },
    { num: '02', title: 'Diseñamos tu propuesta', desc: 'Te mostramos cómo se vería tu web antes de escribir una sola línea de código.' },
    { num: '03', title: 'Desarrollamos', desc: 'Construimos tu web con tecnología moderna, rápida y preparada para crecer.' },
    { num: '04', title: 'Publicamos', desc: 'Tu web queda online, con dominio propio y lista para que te encuentren.' },
    { num: '05', title: 'Te acompañamos', desc: 'Seguimos disponibles para ajustes, mantenimiento y lo que tu negocio necesite después.' },
  ],
  differentiators: {
    headline: 'Una web que realmente te pertenece.',
    text: 'Nada de plantillas armadas a las apuradas. Cada detalle pensado para tu negocio.',
    items: [
      { icon: 'design', title: 'Diseño personalizado', desc: 'Cada web se diseña desde cero para tu marca, no sobre una plantilla genérica.' },
      { icon: 'mobile', title: '100% responsive', desc: 'Se ve perfecta en celular, tablet y computadora, donde te busquen tus clientes.' },
      { icon: 'domain', title: 'Dominio propio', desc: 'Tu propia dirección web, profesional y fácil de recordar.' },
      { icon: 'seo', title: 'Optimizada para Google', desc: 'Preparada para que te encuentren cuando buscan lo que vos ofrecés.' },
      { icon: 'whatsapp', title: 'Integración con WhatsApp', desc: 'Tus clientes te escriben directo, sin formularios complicados.' },
      { icon: 'maps', title: 'Google Maps y redes', desc: 'Ubicación, horarios e Instagram conectados en un mismo lugar.' },
      { icon: 'maintenance', title: 'Hosting y mantenimiento', desc: 'Nos ocupamos de que tu web esté siempre online y funcionando.' },
      { icon: 'code', title: 'Código profesional', desc: 'Tecnología moderna, rápida y preparada para crecer con vos.' },
      { icon: 'automation', title: 'Optimización constante', desc: 'Ajustamos velocidad y experiencia para que nadie se vaya antes de contactarte.' },
    ],
  },
  beforeAfter: {
    eyebrow: 'El cambio',
    headline: 'De "buscame en Instagram" a tener tu propia presencia digital.',
    beforeTitle: 'Antes',
    beforeItems: ['Solo Instagram', 'Sin web propia', 'Difícil de encontrar en Google', 'Catálogo desordenado en el chat'],
    afterTitle: 'Después',
    afterItems: ['Google', 'Instagram', 'Página propia', 'WhatsApp directo', 'Portfolio de trabajos', 'Contacto en un clic'],
  },
  pricing: {
    eyebrow: 'Cómo trabajamos',
    headline: 'Una inversión a la medida de tu negocio.',
    text: 'Cada proyecto es distinto, por eso el presupuesto se arma según lo que tu negocio necesita.',
    tiers: [
      { name: 'Landing Page', desc: 'Una página enfocada en un objetivo: conseguir contactos.', features: ['Diseño a medida', 'Una sola página', 'Optimizada para conversión', 'Integración con WhatsApp'], highlight: false },
      { name: 'Web Profesional', desc: 'La opción más elegida por negocios y profesionales.', features: ['Varias secciones', 'Diseño 100% personalizado', 'SEO básico incluido', 'Panel para editar contenido'], highlight: true },
      { name: 'Proyecto Personalizado', desc: 'Para negocios con necesidades más específicas o complejas.', features: ['Funcionalidades a medida', 'Integraciones avanzadas', 'Automatizaciones', 'Acompañamiento continuo'], highlight: false },
    ],
    ctaLabel: 'Pedir presupuesto',
    disclaimer: 'Cada presupuesto se arma a medida después de conocer tu negocio, sin compromiso.',
  },
  testimonials: [],
  about: {
    heading: 'Tecnología con trato humano.',
    text:
      'Ayudamos a negocios, profesionales y emprendedores a tener una presencia digital profesional, sin complicarlos con aspectos técnicos. Vos nos contás tu idea, nosotros nos encargamos de que se vea, funcione y consiga resultados.',
    ctaLabel: 'Hablemos de tu proyecto',
  },
  cta: {
    tag: 'El momento es ahora',
    titleLine1: 'Tu próximo cliente',
    titleHighlight: 'puede estar buscándote ahora.',
    description: 'Hacé que cuando te encuentre, vea un negocio profesional.',
    cta1Label: 'Quiero mejorar mi presencia digital',
    cta2Label: 'Hablar por WhatsApp',
  },
  contact: {
    headline: 'Contame qué necesitás.',
    text: 'Nosotros nos encargamos del resto. Contános sobre tu negocio y te respondemos a la brevedad.',
    whatsapp: '+543865468239',
    email: 'nmartinez9815@gmail.com',
    storeUrl: 'https://nmtech5.mitiendanube.com/productos/',
    instagramUser: 'nmtechsolutions',
    tiktokUser: 'njmartinez98',
    facebookUser: '',
    location: 'Argentina',
  },
  footer: {
    description:
      'Diseñamos y desarrollamos páginas web modernas para negocios, profesionales y emprendedores que quieren verse profesionales y conseguir más clientes.',
  },
}
